apiVersion: v1
kind: Service
metadata:
  name: wishlist-app
spec:
  type: LoadBalancer
  selector:
    app: wishlist
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8080