performance:
  SpreadOperator:
    active: false
style:
  MagicNumber:
    active: false
exceptions:
  SwallowedException:
    ignoredExceptionTypes:
      - ConstraintViolationException
      - EmptyResultDataAccessException