package dk.cngroup.wishlist.controller

import dk.cngroup.wishlist.entity.ClientRepository
import dk.cngroup.wishlist.entity.Client
import org.springframework.data.rest.webmvc.PersistentEntityResource
import org.springframework.data.rest.webmvc.PersistentEntityResourceAssembler
import org.springframework.data.rest.webmvc.RepositoryRestController
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.RequestParam

//enhancement of /clients endpoint generated by Spring Data REST
@RepositoryRestController
class ClientController(private val repository: ClientRepository) {

    //custom method returning loaded entity in Spring HATEOAS way
    @GetMapping("/clients/client-management/{username}")
    fun getByName(
        @PathVariable username: String,
        resourceAssembler: PersistentEntityResourceAssembler
    ): ResponseEntity<PersistentEntityResource> {
        val client = repository.findClientByUserName(username)
        return ResponseEntity.ok(resourceAssembler.toFullResource(client))
    }

    @GetMapping("/clients/search")
    fun getByProduct(
            @RequestParam productCode: String,
            resourceAssembler: PersistentEntityResourceAssembler
    ) : ResponseEntity<List<Client>>  {
        val clients = repository.findDistinctByWishesProductsCodeOrderByUserName(productCode)
        return ResponseEntity.ok(clients)
    }

}